// Institutions offered as autocomplete on the College field. [name, city].
// Names are canonical and unique so the college leaderboard can group on them.
// Anything not listed can still be typed in; add rows here as they turn up.
window.COLLEGES = [
  ["A V College of Arts, Science and Commerce","Hyderabad"],
  ["Abbas Khan College for Women","Bengaluru"],
  ["ACE Engineering College","Hyderabad"],
  ["Acharya & B M Reddy College of Pharmacy","Bengaluru"],
  ["Acharya Bangalore B-School","Bengaluru"],
  ["Acharya Institute of Graduate Studies","Bengaluru"],
  ["Acharya Institute of Technology","Bengaluru"],
  ["Acharya Narendra Dev College","Delhi"],
  ["Acharya's NRV School of Architecture","Bengaluru"],
  ["Achutha Institute of Technology","Bengaluru"],
  ["ACS College of Engineering","Bengaluru"],
  ["ACS Medical College and Hospital","Chennai"],
  ["Adamas University","Kolkata"],
  ["Adarsha Film & TV Institute","Bengaluru"],
  ["Adarsha Institute of Technology","Bengaluru"],
  ["Aditya College of Engineering","Bengaluru"],
  ["AECS Maaruti College of Dental Sciences","Bengaluru"],
  ["Agni College of Technology","Chennai"],
  ["Agragami College of Aeronautical Engineering","Bengaluru"],
  ["Agurchand Manmull Jain College (AM Jain)","Chennai"],
  ["AIMS Institutes","Bengaluru"],
  ["Akash Global College of Management & Science","Bengaluru"],
  ["Akash Institute of Medical Sciences","Bengaluru"],
  ["Al-Ameen Arts, Science and Commerce College","Bengaluru"],
  ["Al-Ameen College of Law","Bengaluru"],
  ["Al-Ameen College of Pharmacy","Bengaluru"],
  ["Alagappa College of Technology (ACT)","Chennai"],
  ["Aliah University","Kolkata"],
  ["All India Institute of Medical Sciences, Delhi (AIIMS)","Delhi"],
  ["Alliance School of Business","Bengaluru"],
  ["Alliance School of Law","Bengaluru"],
  ["Alliance University","Bengaluru"],
  ["Alpha College of Engineering","Bengaluru"],
  ["Ambedkar Institute of Advanced Communication Technologies and Research","Delhi"],
  ["AMC Engineering College","Bengaluru"],
  ["Amity Law School, Delhi","Delhi"],
  ["Amity University Bengaluru","Bengaluru"],
  ["Amity University, Kolkata","Kolkata"],
  ["Amity University, Noida","Delhi"],
  ["Amrita School of Engineering, Bengaluru","Bengaluru"],
  ["Amrita Vishwa Vidyapeetham, Bengaluru","Bengaluru"],
  ["Anand Institute of Higher Technology","Chennai"],
  ["Anna Adarsh College for Women","Chennai"],
  ["Anna University","Chennai"],
  ["Anupama College of Management and Science","Bengaluru"],
  ["Anurag University","Hyderabad"],
  ["Anwarul Uloom College","Hyderabad"],
  ["Apeejay School of Management","Delhi"],
  ["Apollo Institute of Medical Sciences and Research","Hyderabad"],
  ["APS College of Engineering","Bengaluru"],
  ["Army College of Dental Sciences","Hyderabad"],
  ["Army College of Medical Sciences","Delhi"],
  ["Army Institute of Hotel Management and Catering Technology","Bengaluru"],
  ["Army Institute of Management, Kolkata","Kolkata"],
  ["Aryabhatta College","Delhi"],
  ["ASC Degree College","Bengaluru"],
  ["Ashoka University","Delhi"],
  ["Asian College of Journalism (ACJ)","Chennai"],
  ["Asutosh College","Kolkata"],
  ["Atal Bihari Vajpayee Institute of Medical Sciences (RML)","Delhi"],
  ["Atharva College of Engineering","Mumbai"],
  ["Atma Ram Sanatan Dharma College (ARSD)","Delhi"],
  ["Atria Institute of Technology","Bengaluru"],
  ["Atria University","Bengaluru"],
  ["Aurora's Degree and PG College","Hyderabad"],
  ["Avinash College of Commerce","Hyderabad"],
  ["Ayurvedic Medical College, Bengaluru","Bengaluru"],
  ["Azim Premji University","Bengaluru"],
  ["B P Poddar Institute of Management and Technology","Kolkata"],
  ["B S Abdur Rahman Crescent Institute of Science and Technology","Chennai"],
  ["Badruka College of Commerce and Arts","Hyderabad"],
  ["Baldwin Methodist College","Bengaluru"],
  ["Baldwin Women's Methodist College","Bengaluru"],
  ["Bangabasi College","Kolkata"],
  ["Bangalore City College","Bengaluru"],
  ["Bangalore College of Engineering and Technology","Bengaluru"],
  ["Bangalore Institute of Dental Sciences","Bengaluru"],
  ["Bangalore Institute of Legal Studies (BILS)","Bengaluru"],
  ["Bangalore Institute of Management Studies","Bengaluru"],
  ["Bangalore Institute of Technology (BIT)","Bengaluru"],
  ["Bangalore Medical College and Research Institute (BMCRI)","Bengaluru"],
  ["Bangalore School of Design","Bengaluru"],
  ["Bangalore Technological Institute","Bengaluru"],
  ["Bangalore University","Bengaluru"],
  ["Basanti Devi College","Kolkata"],
  ["Bearys Institute of Technology","Bengaluru"],
  ["Bengaluru City University","Bengaluru"],
  ["Bengaluru North University","Bengaluru"],
  ["BES College","Bengaluru"],
  ["Bethune College","Kolkata"],
  ["BGS Global Institute of Medical Sciences","Bengaluru"],
  ["Bhagini Nivedita College","Delhi"],
  ["Bhagwan Parshuram Institute of Technology (BPIT)","Delhi"],
  ["Bhaktavatsalam Memorial College for Women","Chennai"],
  ["Bharath Institute of Higher Education and Research","Chennai"],
  ["Bharati College","Delhi"],
  ["Bharati Vidyapeeth College of Engineering, Navi Mumbai","Mumbai"],
  ["Bharati Vidyapeeth's College of Engineering, Delhi","Delhi"],
  ["Bhaskar Medical College","Hyderabad"],
  ["Bhaskaracharya College of Applied Sciences","Delhi"],
  ["Bhavan's College, Andheri","Mumbai"],
  ["Bhavan's Priyamvada Birla Institute of Management","Bengaluru"],
  ["Bhavan's Vivekananda College","Hyderabad"],
  ["Bhoj Reddy Engineering College for Women","Hyderabad"],
  ["Bijoy Krishna Girls' College","Kolkata"],
  ["Birla Institute of Management Technology (BIMTECH)","Delhi"],
  ["Bishop Cotton Women's Christian College","Bengaluru"],
  ["Bishop Cotton Women's Christian Law College","Bengaluru"],
  ["BITS Pilani, Hyderabad Campus","Hyderabad"],
  ["BMS College for Women","Bengaluru"],
  ["BMS College of Architecture","Bengaluru"],
  ["BMS College of Engineering","Bengaluru"],
  ["BMS College of Law","Bengaluru"],
  ["BMS Evening College of Engineering","Bengaluru"],
  ["BMS Institute of Technology and Management","Bengaluru"],
  ["BNM Institute of Technology (BNMIT)","Bengaluru"],
  ["Bombay College of Pharmacy","Mumbai"],
  ["Bowring and Lady Curzon Medical College","Bengaluru"],
  ["Brainware University","Kolkata"],
  ["Brindavan College","Bengaluru"],
  ["Brindavan College of Engineering","Bengaluru"],
  ["BTL Institute of Technology and Management","Bengaluru"],
  ["BVRIT Hyderabad College of Engineering for Women","Hyderabad"],
  ["Calcutta Business School","Kolkata"],
  ["Calcutta Institute of Engineering and Management","Kolkata"],
  ["Calcutta National Medical College","Kolkata"],
  ["Cambridge Institute of Technology","Bengaluru"],
  ["Canara Bank School of Management Studies","Bengaluru"],
  ["Cauvery College","Bengaluru"],
  ["Chaitanya Bharathi Institute of Technology (CBIT)","Hyderabad"],
  ["Chanakya University","Bengaluru"],
  ["Charuchandra College","Kolkata"],
  ["Chennai Institute of Technology","Chennai"],
  ["Chennai Mathematical Institute (CMI)","Chennai"],
  ["Chetana's Institute of Management and Research","Mumbai"],
  ["Chetana's Self-Financing Courses","Mumbai"],
  ["Chettinad Academy of Research and Education","Chennai"],
  ["Christ Academy","Bengaluru"],
  ["Christ Academy Institute of Law","Bengaluru"],
  ["Christ University","Bengaluru"],
  ["Christ University Faculty of Engineering","Bengaluru"],
  ["Christ University Institute of Management","Bengaluru"],
  ["City College, Kolkata","Kolkata"],
  ["City Engineering College","Bengaluru"],
  ["Cluster Innovation Centre","Delhi"],
  ["CMR College of Engineering and Technology, Hyderabad","Hyderabad"],
  ["CMR Institute of Management Studies (CMRIMS)","Bengaluru"],
  ["CMR Institute of Technology (CMRIT)","Bengaluru"],
  ["CMR University","Bengaluru"],
  ["CMR University School of Legal Studies","Bengaluru"],
  ["CMS Business School","Bengaluru"],
  ["College of Art, Delhi","Delhi"],
  ["College of Engineering, Guindy (CEG)","Chennai"],
  ["College of Vocational Studies","Delhi"],
  ["Community Institute of Management Studies","Bengaluru"],
  ["CVR College of Engineering","Hyderabad"],
  ["D G Ruparel College","Mumbai"],
  ["D G Vaishnav College","Chennai"],
  ["D Y Patil Medical College, Navi Mumbai","Mumbai"],
  ["Dairy Science College, Hebbal","Bengaluru"],
  ["Datta Meghe College of Engineering","Mumbai"],
  ["Daulat Ram College","Delhi"],
  ["Dayananda Sagar Academy of Technology and Management (DSATM)","Bengaluru"],
  ["Dayananda Sagar Business School","Bengaluru"],
  ["Dayananda Sagar College of Arts, Science and Commerce","Bengaluru"],
  ["Dayananda Sagar College of Dental Sciences","Bengaluru"],
  ["Dayananda Sagar College of Engineering (DSCE)","Bengaluru"],
  ["Dayananda Sagar College of Pharmacy","Bengaluru"],
  ["Dayananda Sagar School of Architecture","Bengaluru"],
  ["Dayananda Sagar University","Bengaluru"],
  ["Deccan College of Engineering and Technology","Hyderabad"],
  ["Deccan College of Medical Sciences","Hyderabad"],
  ["Deen Dayal Upadhyaya College","Delhi"],
  ["Delhi College of Arts and Commerce (DCAC)","Delhi"],
  ["Delhi Institute of Tool Engineering","Delhi"],
  ["Delhi Pharmaceutical Sciences and Research University (DPSRU)","Delhi"],
  ["Delhi School of Business","Delhi"],
  ["Delhi School of Economics","Delhi"],
  ["Delhi Skill and Entrepreneurship University","Delhi"],
  ["Delhi Technological University (DTU)","Delhi"],
  ["Department of Law, University of Calcutta (Hazra)","Kolkata"],
  ["Department of Management Studies, Anna University","Chennai"],
  ["Deshbandhu College","Delhi"],
  ["Dhanalakshmi College of Engineering","Chennai"],
  ["Dinabandhu Andrews College","Kolkata"],
  ["Don Bosco Institute of Technology","Bengaluru"],
  ["Don Bosco Institute of Technology, Mumbai","Mumbai"],
  ["Dr. Ambedkar College of Law","Bengaluru"],
  ["Dr. Ambedkar Government Law College, Chennai","Chennai"],
  ["Dr. Ambedkar Institute of Technology (AIT)","Bengaluru"],
  ["Dr. B R Ambedkar Medical College","Bengaluru"],
  ["Dr. B R Ambedkar Open University","Hyderabad"],
  ["Dr. B R Ambedkar University Delhi (AUD)","Delhi"],
  ["Dr. B. R. Ambedkar School of Economics University (BASE)","Bengaluru"],
  ["Dr. M G R Educational and Research Institute","Chennai"],
  ["Dr. NSAM First Grade College","Bengaluru"],
  ["Dr. R Ahmed Dental College","Kolkata"],
  ["Dr. Ramanah Manohar College of Law","Bengaluru"],
  ["Dr. Syamala Reddy Dental College","Bengaluru"],
  ["Durgadevi Saraf Institute of Management Studies","Mumbai"],
  ["Dwarkadas J. Sanghvi College of Engineering (DJ Sanghvi)","Mumbai"],
  ["Dyal Singh College","Delhi"],
  ["East Point College of Engineering and Technology","Bengaluru"],
  ["East Point College of Medical Sciences","Bengaluru"],
  ["East West College of Engineering","Bengaluru"],
  ["East West College of Pharmacy","Bengaluru"],
  ["East West College of Science","Bengaluru"],
  ["East West Institute of Technology","Bengaluru"],
  ["Easwari Engineering College","Chennai"],
  ["Elphinstone College","Mumbai"],
  ["English and Foreign Languages University (EFLU)","Hyderabad"],
  ["ESI-PGIMSR, Joka","Kolkata"],
  ["ESIC Dental College, Delhi","Delhi"],
  ["ESIC Medical College, Bengaluru","Bengaluru"],
  ["Ethiraj College for Women","Chennai"],
  ["Faculty of Law, University of Delhi (Campus Law Centre)","Delhi"],
  ["Faculty of Management Studies, Delhi (FMS)","Delhi"],
  ["Florence College of Physiotherapy","Bengaluru"],
  ["Florida College of Management and Computer Science","Bengaluru"],
  ["FORE School of Management","Delhi"],
  ["Fr. Conceicao Rodrigues College of Engineering (Fr. CRCE)","Mumbai"],
  ["Future Institute of Engineering and Management","Kolkata"],
  ["G Narayanamma Institute of Technology and Science (GNITS)","Hyderabad"],
  ["Gandhi Medical College","Hyderabad"],
  ["Garden City College","Bengaluru"],
  ["Garden City University","Bengaluru"],
  ["Gargi College","Delhi"],
  ["Geethanjali College of Engineering and Technology","Hyderabad"],
  ["Ghousia College of Engineering","Bengaluru"],
  ["GIBS Business School","Bengaluru"],
  ["GITAM University, Hyderabad","Hyderabad"],
  ["Global Academy of Technology","Bengaluru"],
  ["Globsyn Business School","Kolkata"],
  ["Goenka College of Commerce and Business Administration","Kolkata"],
  ["Gokaraju Rangaraju Institute of Engineering and Technology (GRIET)","Hyderabad"],
  ["Gokhale Memorial Girls' College","Kolkata"],
  ["Gopalan College of Commerce","Bengaluru"],
  ["Gopalan College of Engineering and Management","Bengaluru"],
  ["Gopalan School of Architecture and Planning","Bengaluru"],
  ["Government Arts College, Bengaluru","Bengaluru"],
  ["Government Ayurveda Medical College, Bengaluru","Bengaluru"],
  ["Government City College","Hyderabad"],
  ["Government College of Art and Craft, Kolkata","Kolkata"],
  ["Government College of Engineering and Ceramic Technology","Kolkata"],
  ["Government College of Engineering and Leather Technology","Kolkata"],
  ["Government College of Fine Arts, Chennai","Chennai"],
  ["Government College of Pharmacy","Bengaluru"],
  ["Government Dental College and Research Institute","Bengaluru"],
  ["Government Dental College, Hyderabad","Hyderabad"],
  ["Government Dental College, Mumbai","Mumbai"],
  ["Government First Grade College","Bengaluru"],
  ["Government Institute of Printing Technology","Bengaluru"],
  ["Government Law College, Mumbai","Mumbai"],
  ["Government R C College of Commerce and Management","Bengaluru"],
  ["Government Science College, Bengaluru","Bengaluru"],
  ["Government SKSJ Technological Institute (SKSJTI)","Bengaluru"],
  ["GPS Institute of Agricultural Management","Bengaluru"],
  ["Grant Medical College (JJ Hospital)","Mumbai"],
  ["Great Lakes Institute of Management","Chennai"],
  ["Guru Gobind Singh Indraprastha University (GGSIPU)","Delhi"],
  ["Guru Nanak College, Chennai","Chennai"],
  ["Guru Nanak Institute of Dental Sciences","Kolkata"],
  ["Guru Nanak Institute of Technology","Kolkata"],
  ["Guru Nanak Institutions Technical Campus","Hyderabad"],
  ["Guru Nanak Khalsa College","Mumbai"],
  ["Guru Tegh Bahadur Institute of Technology (GTBIT)","Delhi"],
  ["H B T Medical College (Cooper Hospital)","Mumbai"],
  ["Hamdard Institute of Medical Sciences and Research","Delhi"],
  ["Hansraj College","Delhi"],
  ["Hasanath College for Women","Bengaluru"],
  ["Havnur College of Law","Bengaluru"],
  ["Heramba Chandra College","Kolkata"],
  ["Heritage Institute of Technology","Kolkata"],
  ["Hindu College","Delhi"],
  ["Hindustan Institute of Technology and Science","Chennai"],
  ["HKBK College of Engineering","Bengaluru"],
  ["HMR Institute of Technology and Management","Delhi"],
  ["Homi Bhabha National Institute","Mumbai"],
  ["HR College of Commerce and Economics","Mumbai"],
  ["HSNC University","Mumbai"],
  ["ICFAI Business School, Hyderabad (IBS)","Hyderabad"],
  ["ICFAI Foundation for Higher Education (IFHE)","Hyderabad"],
  ["ICFAI Law School","Hyderabad"],
  ["IES Management College and Research Centre","Mumbai"],
  ["IFIM Business School","Bengaluru"],
  ["IFMR Graduate School of Business (Krea University)","Chennai"],
  ["Impact College of Engineering and Applied Sciences","Bengaluru"],
  ["Indian Academy Degree College","Bengaluru"],
  ["Indian Agricultural Research Institute (IARI)","Delhi"],
  ["Indian Institute of Astrophysics","Bengaluru"],
  ["Indian Institute of Engineering Science and Technology, Shibpur (IIEST)","Kolkata"],
  ["Indian Institute of Fashion Technology","Bengaluru"],
  ["Indian Institute of Foreign Trade, Delhi (IIFT)","Delhi"],
  ["Indian Institute of Foreign Trade, Kolkata (IIFT)","Kolkata"],
  ["Indian Institute of Journalism and New Media (IIJNM)","Bengaluru"],
  ["Indian Institute of Management and Commerce (IIMC Hyderabad)","Hyderabad"],
  ["Indian Institute of Management Bangalore (IIM-B)","Bengaluru"],
  ["Indian Institute of Management Calcutta (IIM Calcutta)","Kolkata"],
  ["Indian Institute of Management Mumbai (IIM Mumbai)","Mumbai"],
  ["Indian Institute of Mass Communication (IIMC)","Delhi"],
  ["Indian Institute of Plantation Management","Bengaluru"],
  ["Indian Institute of Science (IISc)","Bengaluru"],
  ["Indian Institute of Science Education and Research, Kolkata (IISER)","Kolkata"],
  ["Indian Institute of Social Welfare and Business Management (IISWBM)","Kolkata"],
  ["Indian Institute of Technology Bombay (IIT Bombay)","Mumbai"],
  ["Indian Institute of Technology Delhi (IIT Delhi)","Delhi"],
  ["Indian Institute of Technology Hyderabad (IIT Hyderabad)","Hyderabad"],
  ["Indian Institute of Technology Madras (IIT Madras)","Chennai"],
  ["Indian School of Business (ISB)","Hyderabad"],
  ["Indian Statistical Institute Bangalore","Bengaluru"],
  ["Indian Statistical Institute, Delhi","Delhi"],
  ["Indian Statistical Institute, Kolkata","Kolkata"],
  ["Indira Gandhi Delhi Technical University for Women (IGDTUW)","Delhi"],
  ["Indira Gandhi National Open University (IGNOU)","Delhi"],
  ["Indira Priyadarshini College of Law","Bengaluru"],
  ["Indraprastha College for Women","Delhi"],
  ["Indraprastha Institute of Information Technology Delhi (IIIT-Delhi)","Delhi"],
  ["Indus Business Academy (IBA)","Bengaluru"],
  ["Institute for Social and Economic Change (ISEC)","Bengaluru"],
  ["Institute of Aeronautical Engineering (IARE)","Hyderabad"],
  ["Institute of Aerospace Medicine (IAM)","Bengaluru"],
  ["Institute of Chemical Technology (ICT Mumbai)","Mumbai"],
  ["Institute of Engineering and Management (IEM)","Kolkata"],
  ["Institute of Home Economics","Delhi"],
  ["Institute of Hotel Management, Bengaluru (IHM)","Bengaluru"],
  ["Institute of Hotel Management, Chennai (IHM)","Chennai"],
  ["Institute of Hotel Management, Hyderabad (IHM)","Hyderabad"],
  ["Institute of Hotel Management, Kolkata (IHM)","Kolkata"],
  ["Institute of Hotel Management, Mumbai (IHM Dadar)","Mumbai"],
  ["Institute of Hotel Management, Pusa (IHM Pusa)","Delhi"],
  ["Institute of Management Technology, Ghaziabad (IMT)","Delhi"],
  ["Institute of Mathematical Sciences (IMSc)","Chennai"],
  ["Institute of Post Graduate Medical Education and Research (IPGMER, SSKM)","Kolkata"],
  ["Institute of Public Enterprise (IPE)","Hyderabad"],
  ["Institute of Wood Science and Technology","Bengaluru"],
  ["International Institute for Population Sciences (IIPS)","Mumbai"],
  ["International Institute of Business Studies (IIBS)","Bengaluru"],
  ["International Institute of Hotel Management (IIHM)","Bengaluru"],
  ["International Institute of Information Technology Bangalore (IIIT-B)","Bengaluru"],
  ["International Institute of Information Technology, Hyderabad (IIIT-H)","Hyderabad"],
  ["International Management Institute, Delhi (IMI)","Delhi"],
  ["International School of Management Excellence (ISME)","Bengaluru"],
  ["ISBR Business School","Bengaluru"],
  ["Islamiah Institute of Technology","Bengaluru"],
  ["Ismail Yusuf College","Mumbai"],
  ["J B Institute of Engineering and Technology","Hyderabad"],
  ["Jadavpur University","Kolkata"],
  ["Jagan Institute of Management Studies (JIMS)","Delhi"],
  ["Jai Hind College","Mumbai"],
  ["Jain College","Bengaluru"],
  ["Jain University","Bengaluru"],
  ["Jamia Hamdard","Delhi"],
  ["Jamia Millia Islamia","Delhi"],
  ["Jamnalal Bajaj Institute of Management Studies (JBIMS)","Mumbai"],
  ["Janki Devi Memorial College","Delhi"],
  ["Jawaharlal Nehru Architecture and Fine Arts University (JNAFAU)","Hyderabad"],
  ["Jawaharlal Nehru Centre for Advanced Scientific Research (JNCASR)","Bengaluru"],
  ["Jawaharlal Nehru Technological University, Hyderabad (JNTUH)","Hyderabad"],
  ["Jawaharlal Nehru University (JNU)","Delhi"],
  ["Jaypee Institute of Information Technology, Noida","Delhi"],
  ["JD Institute of Fashion Technology","Bengaluru"],
  ["Jeppiaar Engineering College","Chennai"],
  ["Jerusalem College of Engineering","Chennai"],
  ["Jesus and Mary College (JMC)","Delhi"],
  ["Jindal Global Law School","Delhi"],
  ["JIS University","Kolkata"],
  ["Jitendra Chauhan College of Law","Mumbai"],
  ["JNTUH College of Engineering, Hyderabad","Hyderabad"],
  ["Jogamaya Devi College","Kolkata"],
  ["Jogesh Chandra Chaudhuri Law College","Kolkata"],
  ["JSS Academy of Technical Education","Bengaluru"],
  ["Justice Basheer Ahmed Sayeed College for Women (JBAS)","Chennai"],
  ["Jyothy Institute of Technology","Bengaluru"],
  ["Jyoti Nivas College","Bengaluru"],
  ["K C Law College","Mumbai"],
  ["K J Somaiya College of Arts and Commerce","Mumbai"],
  ["K J Somaiya College of Engineering","Mumbai"],
  ["K J Somaiya College of Science and Commerce","Mumbai"],
  ["K J Somaiya Institute of Management (SIMSR)","Mumbai"],
  ["K J Somaiya Medical College","Mumbai"],
  ["K S Institute of Technology (KSIT)","Bengaluru"],
  ["K S School of Engineering and Management","Bengaluru"],
  ["Kalakshetra Foundation","Chennai"],
  ["Kalindi College","Delhi"],
  ["Kalpataru Institute of Technology","Bengaluru"],
  ["Kamala Nehru College","Delhi"],
  ["Kamineni Academy of Medical Sciences","Hyderabad"],
  ["Kamla Raheja Vidyanidhi Institute of Architecture","Mumbai"],
  ["Karnataka Chitrakala Parishath College of Fine Arts","Bengaluru"],
  ["Karnataka College of Pharmacy","Bengaluru"],
  ["Karnataka Samskrit University","Bengaluru"],
  ["Kasturba Gandhi Degree and PG College for Women","Hyderabad"],
  ["KC College","Mumbai"],
  ["KCG College of Technology","Chennai"],
  ["Kelkar Education Trust's V G Vaze College","Mumbai"],
  ["Kempegowda Institute of Management Studies and Research","Bengaluru"],
  ["Kempegowda Institute of Medical Sciences (KIMS)","Bengaluru"],
  ["Kempegowda Institute of Physiotherapy","Bengaluru"],
  ["Ken School of Art","Bengaluru"],
  ["Keshav Mahavidyalaya","Delhi"],
  ["Keshav Memorial Institute of Technology (KMIT)","Hyderabad"],
  ["KG Reddy College of Engineering and Technology","Hyderabad"],
  ["Kilpauk Medical College","Chennai"],
  ["Kirori Mal College","Delhi"],
  ["Kirti M. Doongursee College","Mumbai"],
  ["KL University, Hyderabad","Hyderabad"],
  ["KLE College of Pharmacy, Bengaluru","Bengaluru"],
  ["KLE Society's Institute of Dental Sciences","Bengaluru"],
  ["KLE Society's Law College","Bengaluru"],
  ["KLE Society's S. Nijalingappa College","Bengaluru"],
  ["KNS Institute of Technology","Bengaluru"],
  ["KPC Medical College","Kolkata"],
  ["Krishnadevaraya College of Dental Sciences","Bengaluru"],
  ["Kristu Jayanti College","Bengaluru"],
  ["Kristu Jayanti College of Law","Bengaluru"],
  ["Kristu Jayanti University","Bengaluru"],
  ["Krupanidhi College of Nursing","Bengaluru"],
  ["Krupanidhi College of Pharmacy","Bengaluru"],
  ["Lady Brabourne College","Kolkata"],
  ["Lady Hardinge Medical College","Delhi"],
  ["Lady Irwin College","Delhi"],
  ["Lady Shri Ram College for Women (LSR)","Delhi"],
  ["Lakshmibai College","Delhi"],
  ["Lal Bahadur Shastri Degree College","Bengaluru"],
  ["Lal Bahadur Shastri Institute of Management (LBSIM)","Delhi"],
  ["Lala Lajpatrai College of Commerce and Economics","Mumbai"],
  ["Lokmanya Tilak College of Engineering","Mumbai"],
  ["Lokmanya Tilak Municipal Medical College (Sion Hospital)","Mumbai"],
  ["Loreto College","Kolkata"],
  ["Loyola Academy, Hyderabad","Hyderabad"],
  ["Loyola College, Chennai","Chennai"],
  ["Loyola Institute of Business Administration (LIBA)","Chennai"],
  ["Loyola-ICAM College of Engineering and Technology (LICET)","Chennai"],
  ["M G R Government Film and Television Institute","Chennai"],
  ["M H Saboo Siddik College of Engineering","Mumbai"],
  ["M L Dahanukar College of Commerce","Mumbai"],
  ["M O P Vaishnav College for Women","Chennai"],
  ["M S Ramaiah College of Nursing","Bengaluru"],
  ["M S Ramaiah Dental College","Bengaluru"],
  ["M S Ramaiah Institute of Technology (MSRIT)","Bengaluru"],
  ["M S Ramaiah Medical College","Bengaluru"],
  ["M V S R Engineering College","Hyderabad"],
  ["Madras Christian College (MCC)","Chennai"],
  ["Madras Institute of Technology (MIT Chennai)","Chennai"],
  ["Madras Medical College","Chennai"],
  ["Madras School of Economics","Chennai"],
  ["Madras School of Social Work","Chennai"],
  ["Madras Veterinary College","Chennai"],
  ["Maharaja Agrasen College","Delhi"],
  ["Maharaja Agrasen Institute of Technology (MAIT)","Delhi"],
  ["Maharaja Surajmal Institute of Technology (MSIT)","Delhi"],
  ["Maharani Lakshmi Ammanni College for Women (MLACW)","Bengaluru"],
  ["Maharani's Arts, Commerce and Management College for Women","Bengaluru"],
  ["Maharani's Science College for Women","Bengaluru"],
  ["Maharshi Dayanand College","Mumbai"],
  ["Mahatma Gandhi Institute of Technology (MGIT)","Hyderabad"],
  ["Mahindra University","Hyderabad"],
  ["Maitreyi College","Delhi"],
  ["Malla Reddy Engineering College","Hyderabad"],
  ["Malla Reddy Institute of Medical Sciences","Hyderabad"],
  ["Malla Reddy University","Hyderabad"],
  ["Management Development Institute, Gurgaon (MDI)","Delhi"],
  ["Manipal Academy of Higher Education, Bengaluru","Bengaluru"],
  ["Manipal Institute of Regenerative Medicine","Bengaluru"],
  ["Manipal Institute of Technology, Bengaluru","Bengaluru"],
  ["Mariyappa First Grade College","Bengaluru"],
  ["Marri Laxman Reddy Institute of Technology","Hyderabad"],
  ["Mata Sundri College for Women","Delhi"],
  ["Matrusri Engineering College","Hyderabad"],
  ["Maulana Abul Kalam Azad University of Technology (MAKAUT)","Kolkata"],
  ["Maulana Azad College","Kolkata"],
  ["Maulana Azad Institute of Dental Sciences","Delhi"],
  ["Maulana Azad Medical College (MAMC)","Delhi"],
  ["Maulana Azad National Urdu University (MANUU)","Hyderabad"],
  ["Medical College, Kolkata","Kolkata"],
  ["Mediciti Institute of Medical Sciences","Hyderabad"],
  ["Meenakshi College for Women","Chennai"],
  ["Meenakshi College of Engineering","Chennai"],
  ["Meenakshi Sundararajan Engineering College","Chennai"],
  ["Meghnad Saha Institute of Technology","Kolkata"],
  ["MES College of Arts, Commerce and Science","Bengaluru"],
  ["Methodist College of Engineering and Technology","Hyderabad"],
  ["MGM Medical College, Navi Mumbai","Mumbai"],
  ["Miranda House","Delhi"],
  ["Misrimal Navajee Munoth Jain Engineering College","Chennai"],
  ["Mithibai College","Mumbai"],
  ["MLR Institute of Technology","Hyderabad"],
  ["MMK College of Commerce and Economics","Mumbai"],
  ["Motilal Nehru College","Delhi"],
  ["Mount Carmel College","Bengaluru"],
  ["MP Birla Institute of Management","Bengaluru"],
  ["MS Engineering College","Bengaluru"],
  ["Muffakham Jah College of Engineering and Technology (MJCET)","Hyderabad"],
  ["Mukesh Patel School of Technology Management & Engineering (MPSTME)","Mumbai"],
  ["Mulund College of Commerce","Mumbai"],
  ["Muralidhar Girls' College","Kolkata"],
  ["MVJ College of Engineering","Bengaluru"],
  ["MVJ Medical College and Research Hospital","Bengaluru"],
  ["N K College","Mumbai"],
  ["Nadgir Institute of Engineering and Technology","Bengaluru"],
  ["Nagarjuna College of Engineering and Technology","Bengaluru"],
  ["Nagarjuna Degree College","Bengaluru"],
  ["Nair Hospital Dental College","Mumbai"],
  ["Nalla Malla Reddy Engineering College","Hyderabad"],
  ["NALSAR University of Law","Hyderabad"],
  ["Nandanam Arts College","Chennai"],
  ["Narsee Monjee College of Commerce and Economics (NM College)","Mumbai"],
  ["Narsee Monjee Institute of Management Studies (NMIMS), Bengaluru","Bengaluru"],
  ["Narula Institute of Technology","Kolkata"],
  ["National Centre for Biological Sciences (NCBS)","Bengaluru"],
  ["National College, Basavanagudi","Bengaluru"],
  ["National College, Jayanagar","Bengaluru"],
  ["National Institute of Design Bengaluru (NID)","Bengaluru"],
  ["National Institute of Fashion Technology Bengaluru (NIFT)","Bengaluru"],
  ["National Institute of Fashion Technology, Chennai (NIFT)","Chennai"],
  ["National Institute of Fashion Technology, Delhi (NIFT)","Delhi"],
  ["National Institute of Fashion Technology, Hyderabad (NIFT)","Hyderabad"],
  ["National Institute of Fashion Technology, Kolkata (NIFT)","Kolkata"],
  ["National Institute of Fashion Technology, Mumbai (NIFT)","Mumbai"],
  ["National Institute of Mental Health and Neurosciences (NIMHANS)","Bengaluru"],
  ["National Institute of Pharmaceutical Education and Research, Hyderabad (NIPER)","Hyderabad"],
  ["National Institute of Pharmaceutical Education and Research, Kolkata (NIPER)","Kolkata"],
  ["National Institute of Unani Medicine","Bengaluru"],
  ["National Law School of India University (NLSIU)","Bengaluru"],
  ["National Law University Delhi (NLU Delhi)","Delhi"],
  ["National School of Business","Bengaluru"],
  ["National School of Drama (NSD)","Delhi"],
  ["Neil Gogte Institute of Technology","Hyderabad"],
  ["Netaji Nagar College","Kolkata"],
  ["Netaji Subhas University of Technology (NSUT)","Delhi"],
  ["Netaji Subhash Engineering College","Kolkata"],
  ["New Horizon College of Engineering","Bengaluru"],
  ["New Horizon College, Kasturinagar","Bengaluru"],
  ["Nil Ratan Sircar Medical College (NRS)","Kolkata"],
  ["Nirmala Niketan College of Social Work","Mumbai"],
  ["Nitte College of Pharmaceutical Sciences","Bengaluru"],
  ["Nitte Meenakshi Institute of Technology (NMIT)","Bengaluru"],
  ["Nizam College","Hyderabad"],
  ["NMIMS University, Mumbai","Mumbai"],
  ["NMKRV College for Women","Bengaluru"],
  ["O P Jindal Global University","Delhi"],
  ["Osmania Medical College","Hyderabad"],
  ["Osmania University","Hyderabad"],
  ["Osmania University College for Women (Koti)","Hyderabad"],
  ["Osmania University College of Engineering (OUCE)","Hyderabad"],
  ["Osmania University College of Law","Hyderabad"],
  ["P G D A V College","Delhi"],
  ["Pachaiyappa's College","Chennai"],
  ["Padmashree Institute of Management and Sciences","Bengaluru"],
  ["Panimalar Engineering College","Chennai"],
  ["Panineeya Institute of Dental Sciences","Hyderabad"],
  ["Patkar-Varde College","Mumbai"],
  ["Patrician College of Arts and Science","Chennai"],
  ["Pearl Academy, Bengaluru","Bengaluru"],
  ["Pearl Academy, Delhi","Delhi"],
  ["Pendekanti Law College","Hyderabad"],
  ["PES University","Bengaluru"],
  ["Pillai College of Engineering","Mumbai"],
  ["Potti Sreeramulu Telugu University","Hyderabad"],
  ["Pragati Mahavidyalaya","Hyderabad"],
  ["Prathyusha Engineering College","Chennai"],
  ["Pravin Gandhi College of Law","Mumbai"],
  ["Praxis Business School","Kolkata"],
  ["Presidency College","Bengaluru"],
  ["Presidency College, Chennai","Chennai"],
  ["Presidency University","Bengaluru"],
  ["Presidency University School of Law","Bengaluru"],
  ["Presidency University, Kolkata","Kolkata"],
  ["Quaid-E-Millath Government College for Women","Chennai"],
  ["Queen Mary's College","Chennai"],
  ["R A Podar College of Commerce and Economics","Mumbai"],
  ["R G Kar Medical College","Kolkata"],
  ["R M D Engineering College","Chennai"],
  ["R M K Engineering College","Chennai"],
  ["R R Institute of Technology","Bengaluru"],
  ["R V College of Architecture","Bengaluru"],
  ["R V College of Engineering (RVCE)","Bengaluru"],
  ["Rabindra Bharati University","Kolkata"],
  ["Rachana Sansad Academy of Architecture","Mumbai"],
  ["Rai Technology University","Bengaluru"],
  ["Rajalakshmi Engineering College","Chennai"],
  ["Rajarajeswari College of Engineering","Bengaluru"],
  ["Rajarajeswari Dental College and Hospital","Bengaluru"],
  ["Rajarajeswari Medical College and Hospital","Bengaluru"],
  ["Rajdhani College","Delhi"],
  ["Rajiv Gandhi College of Law","Bengaluru"],
  ["Rajiv Gandhi Institute of Technology","Bengaluru"],
  ["Rajiv Gandhi Institute of Technology, Mumbai","Mumbai"],
  ["Rajiv Gandhi University of Health Sciences (RGUHS)","Bengaluru"],
  ["Ram Lal Anand College","Delhi"],
  ["Ramaiah College of Arts, Science and Commerce","Bengaluru"],
  ["Ramaiah College of Law","Bengaluru"],
  ["Ramaiah Institute of Management","Bengaluru"],
  ["Ramaiah University of Applied Sciences","Bengaluru"],
  ["Ramakrishna Ayurvedic Medical College","Bengaluru"],
  ["Ramakrishna Mission Residential College, Narendrapur","Kolkata"],
  ["Ramakrishna Mission Vidyamandira, Belur","Kolkata"],
  ["Ramakrishna Mission Vivekananda College","Chennai"],
  ["Raman Research Institute","Bengaluru"],
  ["Ramanujan College","Delhi"],
  ["Ramjas College","Delhi"],
  ["Rammohan College","Kolkata"],
  ["Ramnarain Ruia College","Mumbai"],
  ["Ramniranjan Jhunjhunwala College","Mumbai"],
  ["Ramrao Adik Institute of Technology (RAIT)","Mumbai"],
  ["RBANM's First Grade College","Bengaluru"],
  ["RCC Institute of Information Technology","Kolkata"],
  ["Regional Institute of Co-operative Management","Bengaluru"],
  ["REVA University","Bengaluru"],
  ["REVA University School of Legal Studies","Bengaluru"],
  ["Rizvi College of Arts, Science and Commerce","Mumbai"],
  ["Rizvi College of Engineering","Mumbai"],
  ["Rizvi Law College","Mumbai"],
  ["RJS Institute of Management Studies","Bengaluru"],
  ["RNS Institute of Technology (RNSIT)","Bengaluru"],
  ["RPA First Grade College","Bengaluru"],
  ["RR College of Pharmacy","Bengaluru"],
  ["RV Dental College","Bengaluru"],
  ["RV Institute of Management","Bengaluru"],
  ["RV Institute of Technology and Management (RVITM)","Bengaluru"],
  ["RV University","Bengaluru"],
  ["S A Engineering College","Chennai"],
  ["S P Jain Institute of Management and Research (SPJIMR)","Mumbai"],
  ["Sacred Heart Degree College","Bengaluru"],
  ["Sai Vidya Institute of Technology","Bengaluru"],
  ["Sambhram Institute of Technology","Bengaluru"],
  ["Sampoorna Institute of Technology","Bengaluru"],
  ["Sapthagiri College of Engineering","Bengaluru"],
  ["Sapthagiri Institute of Medical Sciences","Bengaluru"],
  ["Sardar Patel College of Engineering (SPCE)","Mumbai"],
  ["Sardar Patel Institute of Technology (SPIT)","Mumbai"],
  ["Sarojini Naidu Vanita Maha Vidyalaya","Hyderabad"],
  ["Sarvodaya Law College","Bengaluru"],
  ["Sathaye College","Mumbai"],
  ["Sathyabama Institute of Science and Technology","Chennai"],
  ["Satyajit Ray Film and Television Institute (SRFTI)","Kolkata"],
  ["Satyawati College","Delhi"],
  ["Saveetha Engineering College","Chennai"],
  ["Saveetha Institute of Medical and Technical Sciences","Chennai"],
  ["Saveetha School of Law","Chennai"],
  ["School of Excellence in Law (TNDALU)","Chennai"],
  ["School of Planning and Architecture, Delhi (SPA)","Delhi"],
  ["Scottish Church College","Kolkata"],
  ["SDNB Vaishnav College for Women","Chennai"],
  ["SEA College of Engineering and Technology","Bengaluru"],
  ["Seshadripuram College","Bengaluru"],
  ["Seshadripuram Commerce College","Bengaluru"],
  ["Seshadripuram First Grade College","Bengaluru"],
  ["Seshadripuram Law College","Bengaluru"],
  ["Seth Anandram Jaipuria College","Kolkata"],
  ["Seth G S Medical College (KEM Hospital)","Mumbai"],
  ["Shadan Institute of Medical Sciences","Hyderabad"],
  ["Shah & Anchor Kutchhi Engineering College","Mumbai"],
  ["Shaheed Bhagat Singh College","Delhi"],
  ["Shaheed Rajguru College of Applied Sciences for Women","Delhi"],
  ["Shaheed Sukhdev College of Business Studies (SSCBS)","Delhi"],
  ["Sheshadripuram Academy of Business Studies","Bengaluru"],
  ["Sheshadripuram Institute of Management","Bengaluru"],
  ["Shirdi Sai Engineering College","Bengaluru"],
  ["Shiv Nadar University","Delhi"],
  ["Shivaji College","Delhi"],
  ["Shri Ram College of Commerce (SRCC)","Delhi"],
  ["Shri Shankarlal Sundarbai Shasun Jain College for Women","Chennai"],
  ["Shri Shikshayatan College","Kolkata"],
  ["Shyam Lal College","Delhi"],
  ["Shyama Prasad Mukherji College for Women","Delhi"],
  ["Siddharth College of Arts, Science and Commerce","Mumbai"],
  ["SIES College of Arts, Science and Commerce","Mumbai"],
  ["SIES College of Management Studies","Mumbai"],
  ["Sindhi College","Bengaluru"],
  ["Sir J J College of Architecture","Mumbai"],
  ["Sir J J School of Art","Mumbai"],
  ["Sir M Visvesvaraya Institute of Technology (Sir MVIT)","Bengaluru"],
  ["Sister Nivedita University","Kolkata"],
  ["Siva Sivani Institute of Management","Hyderabad"],
  ["Sivanath Sastri College","Kolkata"],
  ["SJB Institute of Technology","Bengaluru"],
  ["SJR College of Law","Bengaluru"],
  ["Smt. VHD Central Institute of Home Science","Bengaluru"],
  ["SNDT Women's University","Mumbai"],
  ["Somaiya Vidyavihar University","Mumbai"],
  ["Sophia College for Women","Mumbai"],
  ["Sophia Shree B K Somani Polytechnic","Mumbai"],
  ["Soundarya Institute of Management and Science","Bengaluru"],
  ["South Asian University","Delhi"],
  ["South Calcutta Law College","Kolkata"],
  ["Sree Balaji Medical College","Chennai"],
  ["Sreenidhi Institute of Science and Technology (SNIST)","Hyderabad"],
  ["Sreyas Institute of Engineering and Technology","Hyderabad"],
  ["Sri Aurobindo College","Delhi"],
  ["Sri Bhagawan Mahaveer Jain College","Bengaluru"],
  ["Sri Guru Gobind Singh College of Commerce","Delhi"],
  ["Sri Guru Tegh Bahadur Khalsa College","Delhi"],
  ["Sri Kanyaka Parameswari Arts and Science College for Women","Chennai"],
  ["Sri Kengal Hanumanthaiah Law College","Bengaluru"],
  ["Sri Krishna Degree College","Bengaluru"],
  ["Sri Krishna Institute of Technology","Bengaluru"],
  ["Sri Rajiv Gandhi College of Dental Sciences","Bengaluru"],
  ["Sri Ramachandra Institute of Higher Education and Research","Chennai"],
  ["Sri Revana Siddeshwara Institute of Technology","Bengaluru"],
  ["Sri Sairam College of Engineering","Bengaluru"],
  ["Sri Sairam Engineering College, Chennai","Chennai"],
  ["Sri Sivasubramaniya Nadar College of Engineering (SSN)","Chennai"],
  ["Sri Venkateshwara College of Engineering","Bengaluru"],
  ["Sri Venkateswara College of Engineering, Chennai (SVCE)","Chennai"],
  ["Sri Venkateswara College, Delhi","Delhi"],
  ["Srishti Manipal Institute of Art, Design and Technology","Bengaluru"],
  ["SRM Institute of Science and Technology","Chennai"],
  ["Srushti Degree College","Bengaluru"],
  ["SSMRV College","Bengaluru"],
  ["St. Andrew's College, Bandra","Mumbai"],
  ["St. Ann's College for Women","Hyderabad"],
  ["St. Anne's Degree College for Women","Bengaluru"],
  ["St. Claret College","Bengaluru"],
  ["St. Francis College for Women","Hyderabad"],
  ["St. Francis de Sales College (SFS)","Bengaluru"],
  ["St. Francis Institute of Technology","Mumbai"],
  ["St. John's College of Nursing","Bengaluru"],
  ["St. John's Medical College","Bengaluru"],
  ["St. Joseph's College of Business Administration","Bengaluru"],
  ["St. Joseph's College of Commerce","Bengaluru"],
  ["St. Joseph's College of Engineering, Chennai","Chennai"],
  ["St. Joseph's College of Law","Bengaluru"],
  ["St. Joseph's Degree and PG College, Hyderabad","Hyderabad"],
  ["St. Joseph's Evening College","Bengaluru"],
  ["St. Joseph's Institute of Management","Bengaluru"],
  ["St. Joseph's University","Bengaluru"],
  ["St. Martin's Engineering College","Hyderabad"],
  ["St. Mary's College, Hyderabad","Hyderabad"],
  ["St. Paul's Cathedral Mission College","Kolkata"],
  ["St. Paul's College, Bengaluru","Bengaluru"],
  ["St. Pious X Degree College for Women","Hyderabad"],
  ["St. Stephen's College","Delhi"],
  ["St. Xavier's College, Kolkata","Kolkata"],
  ["St. Xavier's College, Mumbai","Mumbai"],
  ["St. Xavier's University, Kolkata","Kolkata"],
  ["Stanley College of Engineering and Technology for Women","Hyderabad"],
  ["Stanley Medical College","Chennai"],
  ["Stella Maris College","Chennai"],
  ["Sultan-ul-Uloom College of Law","Hyderabad"],
  ["Surana College","Bengaluru"],
  ["Surendranath College","Kolkata"],
  ["Surendranath Law College","Kolkata"],
  ["Sushant School of Art and Architecture","Delhi"],
  ["Swami Shraddhanand College","Delhi"],
  ["Sydenham College of Commerce and Economics","Mumbai"],
  ["Symbiosis Institute of Business Management, Bengaluru","Bengaluru"],
  ["Symbiosis Law School, Hyderabad","Hyderabad"],
  ["T John Institute of Technology","Bengaluru"],
  ["Tagore Engineering College","Chennai"],
  ["Tagore Medical College","Chennai"],
  ["Tamil Nadu Dr. Ambedkar Law University","Chennai"],
  ["Tamil Nadu Dr. M G R Medical University","Chennai"],
  ["Tamil Nadu Veterinary and Animal Sciences University (TANUVAS)","Chennai"],
  ["Tata Institute of Fundamental Research (TIFR)","Mumbai"],
  ["Tata Institute of Fundamental Research, Hyderabad","Hyderabad"],
  ["Tata Institute of Social Sciences (TISS)","Mumbai"],
  ["Techno India University","Kolkata"],
  ["Techno Main Salt Lake","Kolkata"],
  ["TERI School of Advanced Studies","Delhi"],
  ["Terna Engineering College","Mumbai"],
  ["Thadomal Shahani Engineering College (TSEC)","Mumbai"],
  ["Thakur College of Engineering and Technology","Mumbai"],
  ["Thakur College of Science and Commerce","Mumbai"],
  ["The Bhawanipur Education Society College","Kolkata"],
  ["The New College, Chennai","Chennai"],
  ["The Oxford College of Arts","Bengaluru"],
  ["The Oxford College of Business Management","Bengaluru"],
  ["The Oxford College of Engineering","Bengaluru"],
  ["The Oxford College of Hotel Management","Bengaluru"],
  ["The Oxford College of Science","Bengaluru"],
  ["The Oxford Dental College","Bengaluru"],
  ["The Oxford Medical College","Bengaluru"],
  ["TKR College of Engineering and Technology","Hyderabad"],
  ["Topiwala National Medical College (Nair Hospital)","Mumbai"],
  ["Trans-Disciplinary University (TDU)","Bengaluru"],
  ["Umeschandra College","Kolkata"],
  ["United Mission Degree College","Bengaluru"],
  ["University College of Medical Sciences (UCMS)","Delhi"],
  ["University Law College, Bangalore University","Bengaluru"],
  ["University of Agricultural Sciences, Bangalore (GKVK)","Bengaluru"],
  ["University of Calcutta","Kolkata"],
  ["University of Delhi (DU)","Delhi"],
  ["University of Engineering and Management, Kolkata (UEM)","Kolkata"],
  ["University of Hyderabad (HCU)","Hyderabad"],
  ["University of Madras","Chennai"],
  ["University of Mumbai","Mumbai"],
  ["University School of Law and Legal Studies (GGSIPU)","Delhi"],
  ["University Visvesvaraya College of Engineering (UVCE)","Bengaluru"],
  ["V S Dental College","Bengaluru"],
  ["V V Puram College of Arts and Commerce","Bengaluru"],
  ["Valliammai Engineering College","Chennai"],
  ["Vanguard Business School","Bengaluru"],
  ["Vardhaman College of Engineering","Hyderabad"],
  ["Vardhman Mahavir Medical College (Safdarjung)","Delhi"],
  ["Vasavi College of Engineering","Hyderabad"],
  ["Veermata Jijabai Technological Institute (VJTI)","Mumbai"],
  ["Vel Tech Rangarajan Dr. Sagunthala R&D Institute","Chennai"],
  ["Velammal Engineering College","Chennai"],
  ["Vels Institute of Science, Technology and Advanced Studies (VISTAS)","Chennai"],
  ["Vemana Institute of Technology","Bengaluru"],
  ["VES College of Arts, Science and Commerce","Mumbai"],
  ["VET First Grade College","Bengaluru"],
  ["Veterinary College, Hebbal","Bengaluru"],
  ["Vidya Jyothi Institute of Technology (VJIT)","Hyderabad"],
  ["Vidya Vardhaka Sangha First Grade College","Bengaluru"],
  ["Vidyalankar Institute of Technology","Mumbai"],
  ["Vidyasagar College","Kolkata"],
  ["Vidyashilp University","Bengaluru"],
  ["Vignana Bharathi Institute of Technology (VBIT)","Hyderabad"],
  ["Vignana Jyothi Institute of Management","Hyderabad"],
  ["Vijaya College","Bengaluru"],
  ["Vijaya Vittala Institute of Technology","Bengaluru"],
  ["Villa Marie College for Women","Hyderabad"],
  ["Visveswarapura Institute of Pharmaceutical Sciences","Bengaluru"],
  ["VIT Chennai","Chennai"],
  ["Vivekanand College, Chembur","Mumbai"],
  ["Vivekanand Education Society's Institute of Technology (VESIT)","Mumbai"],
  ["Vivekananda College of Law","Bengaluru"],
  ["Vivekananda College, Chennai","Chennai"],
  ["Vivekananda College, Delhi","Delhi"],
  ["Vivekananda Degree College","Bengaluru"],
  ["Vivekananda Institute of Professional Studies (VIPS)","Delhi"],
  ["Vivekananda Institute of Technology","Bengaluru"],
  ["VNR Vignana Jyothi Institute of Engineering and Technology (VNRVJIET)","Hyderabad"],
  ["Vogue Institute of Art and Design","Bengaluru"],
  ["Vydehi Institute of Dental Sciences","Bengaluru"],
  ["Vydehi Institute of Medical Sciences and Research Centre","Bengaluru"],
  ["Welingkar Institute of Management, Bengaluru","Bengaluru"],
  ["Welingkar Institute of Management, Mumbai","Mumbai"],
  ["Wesley Degree College","Hyderabad"],
  ["West Bengal National University of Juridical Sciences (NUJS)","Kolkata"],
  ["West Bengal State University","Kolkata"],
  ["Whistling Woods International","Mumbai"],
  ["Wilson College","Mumbai"],
  ["Women's Christian College (WCC)","Chennai"],
  ["Woxsen University","Hyderabad"],
  ["Xavier Institute of Communications (XIC)","Mumbai"],
  ["Xavier Institute of Engineering","Mumbai"],
  ["Xavier Institute of Management and Entrepreneurship (XIME)","Bengaluru"],
  ["Xavier Institute of Management and Research (XIMR)","Mumbai"],
  ["Yellamma Dasappa Institute of Technology","Bengaluru"],
  ["Zakir Husain Delhi College","Delhi"],
  ["Zee Institute of Creative Arts (ZICA)","Bengaluru"]
];
